import { pgTable, text, uuid, boolean, timestamp, date } from 'drizzle-orm/pg-core'

export const founders = pgTable('founders', {
  id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), founderLinkedinUrl: text('founder_linkedin_url'), companyName: text('company_name').notNull(), companyLinkedinUrl: text('company_linkedin_url'), companyWebsite: text('company_website'), privateNotes: text('private_notes'), status: text('status').notNull().default('DISCOVERED'), researchDepth: text('research_depth'), askText: text('ask_text'), askApproved: boolean('ask_approved').notNull().default(false), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow(),
})
export const researchReports = pgTable('research_reports', { id: uuid('id').defaultRandom().primaryKey(), founderId: uuid('founder_id').notNull(), founderBackground: text('founder_background'), founderWhy: text('founder_why'), companyWhat: text('company_what'), companyWhy: text('company_why'), companyHow: text('company_how'), whoItServes: text('who_it_serves'), currentStage: text('current_stage'), currentFocus: text('current_focus'), facts: text('facts'), inferences: text('inferences'), unknowns: text('unknowns'), privateNoteClaims: text('private_note_claims'), depth: text('depth'), depthReason: text('depth_reason'), askText: text('ask_text'), createdAt: timestamp('created_at').notNull().defaultNow() })
export const researchEvidence = pgTable('research_evidence', { id: uuid('id').defaultRandom().primaryKey(), founderId: uuid('founder_id').notNull(), reportId: uuid('report_id'), claimType: text('claim_type').notNull(), claim: text('claim').notNull(), sourceTitle: text('source_title'), sourceUrl: text('source_url'), excerpt: text('excerpt'), createdAt: timestamp('created_at').notNull().defaultNow() })
export const founderEvents = pgTable('founder_events', { id: uuid('id').defaultRandom().primaryKey(), founderId: uuid('founder_id').notNull(), status: text('status').notNull(), note: text('note'), createdAt: timestamp('created_at').notNull().defaultNow() })
export const applications = pgTable('applications', { id: uuid('id').defaultRandom().primaryKey(), company: text('company').notNull(), role: text('role'), jobUrl: text('job_url'), applicationPlatform: text('application_platform'), dateApplied: date('date_applied'), status: text('status').notNull().default('FOUND'), researchDepth: text('research_depth'), documentsUsed: text('documents_used'), notes: text('notes'), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const researchRuns = pgTable('research_runs', { id: uuid('id').defaultRandom().primaryKey(), founderId: uuid('founder_id').notNull(), state: text('state').notNull().default('{}'), trace: text('trace').notNull().default('[]'), budget: text('budget').notNull().default('{}'), stopReason: text('stop_reason'), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const researchLlmCalls = pgTable('research_llm_calls', { id: uuid('id').defaultRandom().primaryKey(), runId: uuid('run_id').notNull(), founderId: uuid('founder_id').notNull(), stage: text('stage').notNull(), action: text('action'), model: text('model').notNull(), inputTokens: text('input_tokens'), outputTokens: text('output_tokens'), totalTokens: text('total_tokens'), latencyMs: text('latency_ms'), success: boolean('success').notNull().default(false), rateLimit: text('rate_limit'), error: text('error'), createdAt: timestamp('created_at').notNull().defaultNow() })
export const researchTrace = pgTable('research_trace', { id: uuid('id').defaultRandom().primaryKey(), runId: uuid('run_id').notNull(), founderId: uuid('founder_id').notNull(), event: text('event').notNull(), detail: text('detail'), action: text('action'), createdAt: timestamp('created_at').notNull().defaultNow() })
