import { NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { founders, researchEvidence, researchReports, founderEvents, researchRuns } from '@/lib/db/schema'
 import { eq } from 'drizzle-orm'
 import { initialState, addTrace, saveRun, mechanicalFilter, researchConfig, chooseModel, estimateTokens, canAfford, postingPattern, shouldStop, updateMechanicalState, unresolvedQuestions, stopReason, selectNextBatch } from '@/lib/research-engine'

type Source = { title: string; url: string; excerpt: string; sourceType: string; retrievedAt: string; author?: string; publishedAt?: string; retrievalStatus?: 'FOUND' | 'UNAVAILABLE'; provider?: string }

type BrightDataDiagnostics = { requestUrl: string; requestPayload: { url: string }; requestStatus: string; responseStatus: number | null; authentication: 'CONFIGURED' | 'MISSING' | 'REJECTED'; endpoint: string; synchronousMode: 'SUPPORTED' | 'NOT_USED' | 'UNKNOWN'; recordsReturned: number; profileRecords: number; postRecords: number; sourceUrls: string[]; providerError?: { code?: string; message?: string }; rawRecords?: unknown[]; }
let lastBrightDataDiagnostics: BrightDataDiagnostics | undefined

function brightDataError(code: string | undefined, message: string | undefined) {
  return { code, message: message || 'Bright Data returned an unspecified provider error.' }
}

async function collectBrightDataLinkedIn(url: string, founderName: string): Promise<Source[]> {
  const endpoint = 'https://api.brightdata.com/datasets/v3/scrape'
  const datasetId = process.env.BRIGHTDATA_LINKEDIN_DATASET_ID || 'gd_l1viktl72bvl7bjuj0'
  lastBrightDataDiagnostics = { requestUrl: `${endpoint}?dataset_id=${encodeURIComponent(datasetId)}&format=json`, requestPayload: { url }, requestStatus: 'STARTED', responseStatus: null, authentication: process.env.BRIGHTDATA_API_KEY ? 'CONFIGURED' : 'MISSING', endpoint: `${endpoint} (dataset_id=${datasetId})`, synchronousMode: 'NOT_USED', recordsReturned: 0, profileRecords: 0, postRecords: 0, sourceUrls: [] }
  if (!process.env.BRIGHTDATA_API_KEY) { lastBrightDataDiagnostics.requestStatus = 'NOT_CONFIGURED'; throw new Error('Bright Data API key is not configured.') }
  const response = await fetch(lastBrightDataDiagnostics.requestUrl, {
    method: 'POST', headers: { Authorization: `Bearer ${process.env.BRIGHTDATA_API_KEY}`, 'Content-Type': 'application/json' },
    body: JSON.stringify([{ url }]), signal: AbortSignal.timeout(30000),
  })
  lastBrightDataDiagnostics.responseStatus = response.status
  const responseText = await response.text()
  let payload: any
  try { payload = JSON.parse(responseText) } catch { payload = { raw: responseText } }
  if (!response.ok) {
    lastBrightDataDiagnostics.requestStatus = 'FAILED'
    lastBrightDataDiagnostics.authentication = response.status === 401 || response.status === 403 ? 'REJECTED' : 'CONFIGURED'
    lastBrightDataDiagnostics.providerError = brightDataError(payload?.error?.code || payload?.code || payload?.error_code, payload?.error?.message || payload?.message || payload?.error_message || responseText.slice(0, 1000))
    console.log('[v0] Bright Data diagnostics', JSON.stringify(lastBrightDataDiagnostics))
    throw new Error(`Bright Data collection failed (${response.status}): ${lastBrightDataDiagnostics.providerError.message}`)
  }
  lastBrightDataDiagnostics.requestStatus = 'ACCEPTED'
  console.log('[v0] Bright Data diagnostics', JSON.stringify({ ...lastBrightDataDiagnostics, responseBody: responseText.slice(0, 12000) }))
  const directRows = Array.isArray(payload) ? payload : payload.data || payload.results || payload.records || payload.items || payload.snapshot || payload.result
  if (Array.isArray(directRows)) {
    lastBrightDataDiagnostics.recordsReturned = directRows.length
    lastBrightDataDiagnostics.profileRecords = directRows.length ? 1 : 0
    lastBrightDataDiagnostics.postRecords = Math.max(0, directRows.length - (directRows.length ? 1 : 0))
    lastBrightDataDiagnostics.sourceUrls = directRows.map((row: any) => row.url || row.linkedin_url || row.post_url || url).filter(Boolean)
    lastBrightDataDiagnostics.requestStatus = 'COMPLETE'
    lastBrightDataDiagnostics.rawRecords = directRows.slice(0, 5)
    console.log('[v0] Bright Data diagnostics complete', JSON.stringify(lastBrightDataDiagnostics))
    if (!directRows.length) return [{ title: `${founderName} LinkedIn collection`, url, excerpt: 'Bright Data returned no public profile rows.', sourceType: 'LINKEDIN PROFILE', retrievedAt: new Date().toISOString(), retrievalStatus: 'UNAVAILABLE', provider: 'Bright Data' }]
    return directRows.map((row: any, index: number) => ({ title: row.name || row.full_name || `${founderName} LinkedIn data`, url: row.url || row.linkedin_url || url, excerpt: JSON.stringify(row).slice(0, 14000), sourceType: index === 0 ? 'LINKEDIN PROFILE' : 'LINKEDIN PUBLIC ACTIVITY', retrievedAt: new Date().toISOString(), author: row.name || row.full_name, publishedAt: row.date || row.post_date, retrievalStatus: 'FOUND', provider: 'Bright Data' }))
  }
  const snapshotId = payload.snapshot_id || payload.snapshotId || payload.id
  if (!snapshotId) throw new Error('Bright Data returned no snapshot ID.')
  const started = Date.now()
  let rows: any[] = []
  while (Date.now() - started < 90000) {
    await new Promise(resolve => setTimeout(resolve, 4000))
    const result = await fetch(`https://api.brightdata.com/datasets/v3/snapshot/${encodeURIComponent(snapshotId)}?format=json`, { headers: { Authorization: `Bearer ${process.env.BRIGHTDATA_API_KEY}` }, signal: AbortSignal.timeout(30000) })
    if (result.status === 202) continue
    if (!result.ok) throw new Error(`Bright Data snapshot failed (${result.status}).`)
    const snapshotText = await result.text()
    let data: any
    try { data = JSON.parse(snapshotText) } catch { data = { raw: snapshotText } }
    rows = Array.isArray(data) ? data : data.data || data.results || []
    lastBrightDataDiagnostics.responseStatus = result.status
    lastBrightDataDiagnostics.recordsReturned = rows.length
    lastBrightDataDiagnostics.profileRecords = rows.length ? 1 : 0
    lastBrightDataDiagnostics.postRecords = Math.max(0, rows.length - (rows.length ? 1 : 0))
    lastBrightDataDiagnostics.sourceUrls = rows.map((row: any) => row.url || row.linkedin_url || row.post_url || url).filter(Boolean)
    lastBrightDataDiagnostics.requestStatus = rows.length ? 'COMPLETE' : 'EMPTY'
    lastBrightDataDiagnostics.rawRecords = rows.slice(0, 5)
    console.log('[v0] Bright Data snapshot diagnostics', JSON.stringify({ ...lastBrightDataDiagnostics, responseBody: snapshotText.slice(0, 12000) }))
    break
  }
  if (!rows.length) return [{ title: `${founderName} LinkedIn collection`, url, excerpt: 'Bright Data returned no public profile rows.', sourceType: 'LINKEDIN PROFILE', retrievedAt: new Date().toISOString(), retrievalStatus: 'UNAVAILABLE', provider: 'Bright Data' }]
  return rows.map((row, index) => ({ title: row.name || row.full_name || `${founderName} LinkedIn data`, url: row.url || row.linkedin_url || url, excerpt: JSON.stringify(row).slice(0, 14000), sourceType: index === 0 ? 'LINKEDIN PROFILE' : 'LINKEDIN PUBLIC ACTIVITY', retrievedAt: new Date().toISOString(), author: row.name || row.full_name, publishedAt: row.date || row.post_date, retrievalStatus: 'FOUND', provider: 'Bright Data' }))
}
type Report = { founderBackground:string; founderWhy:string; companyWhat:string; companyWhy:string; companyHow:string; whoItServes:string; currentStage:string; currentFocus:string; facts:string; inferences:string; unknowns:string; privateNoteClaims:string; depth:string; depthReason:string; askText:string }
type Pipeline = { webResearch: 'COMPLETE'|'FAILED'; sourcesCollected:number; brightData: 'COMPLETE'|'FAILED'|'NOT_CONFIGURED'; founderProfile: 'FOUND'|'NOT_FOUND'|'NOT_ATTEMPTED'; founderPosts:number; company: 'FOUND'|'NOT_FOUND'|'NOT_ATTEMPTED'; companyPosts:number; coFoundersIdentified:number; coFounderPosts:number; groqSynthesis:'COMPLETE'|'FAILED'; modelUsed:string; structuredOutput:'VALID'|'INVALID'; askGeneration:'COMPLETE'|'FAILED'; error?:string; brightDataDiagnostics?: BrightDataDiagnostics }
const model = chooseModel('FINAL_SYNTHESIS', researchConfig().finalBudget)
const clean = (html:string) => html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>|<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()
const titleOf = (html:string, fallback:string) => html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/\s+/g,' ').trim() || fallback
async function readSource(url:string, fallback:string, sourceType='SUPPLIED URL'):Promise<Source|null>{ try { const r=await fetch(url,{headers:{'user-agent':'FounderOS/1.0 public research collector'},redirect:'follow',signal:AbortSignal.timeout(12000)}); if(!r.ok)return null; const html=await r.text(); const excerpt=clean(html).slice(0,14000); return excerpt?{title:titleOf(html,fallback),url:r.url||url,excerpt,sourceType,retrievedAt:new Date().toISOString()}:null } catch{return null} }
async function searchPublic(query:string){ try { const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`,{headers:{'user-agent':'FounderOS/1.0 public research collector'},signal:AbortSignal.timeout(12000)}); if(!r.ok)return[]; const html=await r.text(); const matches=[...html.matchAll(/<a rel="nofollow" class="result__a" href="([^"]+)">([\s\S]*?)<\/a>/g)].slice(0,6); const out:Source[]=[]; for(const m of matches){const url=m[1].replace(/&amp;/g,'&'); if(/^https?:\/\//.test(url)){const s=await readSource(url,clean(m[2]),'PUBLIC WEB SEARCH');if(s)out.push(s)}} return out } catch{return[]} }
function discoverFromEvidence(items:Source[]){
  const text=items.map(s=>`${s.title}\n${s.excerpt}`).join('\n');
  const companyMatches=[...text.matchAll(/(?:company|works? at|founder of|co[- ]?founder of|building)[:\s]+([A-Z][A-Za-z0-9&.'-]{1,40}(?:\s+[A-Z][A-Za-z0-9&.'-]{1,40}){0,3})/g)].map(m=>m[1].trim()).filter(x=>!/^LinkedIn$/i.test(x));
  const linkedin=[...text.matchAll(/https?:\/\/(?:www\.)?linkedin\.com\/(?:company|in)\/[A-Za-z0-9._-]+/gi)].map(m=>m[0]);
  const websites=[...text.matchAll(/https?:\/\/(?!www\.linkedin\.com)[A-Za-z0-9.-]+\.[A-Za-z]{2,}(?:\/[A-Za-z0-9._~:/?#\[\]@!$&'()*+,;=%-]*)?/g)].map(m=>m[0]);
  return {companyName:companyMatches.find(x=>x.length>2),companyLinkedinUrl:linkedin.find(x=>/\/company\//i.test(x)),companyWebsite:websites.find(x=>!/(duckduckgo|brightdata|ycombinator)/i.test(x))};
}
const base = (f:any, n:number):Report=>({founderBackground:'UNKNOWN — no directly supported background claim was established.',founderWhy:'UNKNOWN — no direct public statement establishing why this founder started the company was established.',companyWhat:n?`UNKNOWN — review the evidence map; the model did not complete synthesis.`:'UNKNOWN — no accessible company source.',companyWhy:'UNKNOWN — not established by the available evidence.',companyHow:'UNKNOWN — not established by the available evidence.',whoItServes:'UNKNOWN — not established by the available evidence.',currentStage:'UNKNOWN — not assigned without evidence.',currentFocus:'UNKNOWN — not established by recent evidence.',facts:n?`FACT — ${n} source${n===1?'':'s'} collected; see the source list.`:'FACT — no usable public source collected.',inferences:'UNKNOWN — synthesis was not completed.',unknowns:'The structured report remains unavailable until Groq synthesis succeeds.',privateNoteClaims:f.privateNotes?`PRIVATE HYPOTHESIS — ${f.privateNotes}\nASSESSMENT — Not established.`:'No private hypothesis recorded.',depth:'LIMITED_INFORMATION_ASK',depthReason:'The evidence could not be synthesized into a validated report.',askText:`Hi ${f.name.split(' ')[0]}, I came across ${f.companyName} and would love to understand what you’re building and focused on right now. I’m 18 and looking to get into an early-stage environment where I can contribute while learning from the real building process. If you’re open to it, I’d love to ask a few questions.`})
function parseReport(value:string, f:any, n:number):Report|null { try { const raw=value.replace(/^```(?:json)?\s*|\s*```$/g,'').trim(); const start=raw.indexOf('{'); const end=raw.lastIndexOf('}'); if(start<0||end<start)return null; const source=JSON.parse(raw.slice(start,end+1)); const parsed=source.report&&typeof source.report==='object'?source.report:source; const text=(v:unknown)=>Array.isArray(v)?v.map(x=>typeof x==='string'?x:JSON.stringify(x)).join('\\n'):typeof v==='string'?v:''; const nested=(...paths:string[])=>{let v:any=parsed; for(const path of paths){v=v?.[path]} return v}; const normalized:Report={founderBackground:text(parsed.founderBackground??nested('founder','background')),founderWhy:text(parsed.founderWhy??nested('founder','founder_why')??nested('founder','why')),companyWhat:text(parsed.companyWhat??nested('company','what')),companyWhy:text(parsed.companyWhy??nested('company','why')),companyHow:text(parsed.companyHow??nested('company','how')),whoItServes:text(parsed.whoItServes??nested('company','customers')??nested('company','who_it_serves')),currentStage:text(parsed.currentStage??nested('company','current_stage')),currentFocus:text(parsed.currentFocus??nested('company','current_focus')),facts:text(parsed.facts??nested('certainty','facts')),inferences:text(parsed.inferences??nested('certainty','inferences')),unknowns:text(parsed.unknowns??nested('certainty','unknowns')),privateNoteClaims:text(parsed.privateNoteClaims??nested('certainty','private_note_claims')),depth:text(parsed.depth??nested('research','depth')),depthReason:text(parsed.depthReason??nested('research','reason_for_depth')),askText:text(parsed.askText??nested('ask','draft_message'))}; const keys=['founderBackground','founderWhy','companyWhat','companyWhy','companyHow','whoItServes','currentStage','currentFocus','facts','inferences','unknowns','privateNoteClaims','depth','depthReason','askText']; if(keys.some(k=>!normalized[k as keyof Report]))return null; if(!['DEEP_RESEARCH_ASK','LIGHT_RESEARCH_ASK','LIMITED_INFORMATION_ASK','SKIP'].includes(normalized.depth))return null; return normalized } catch{return null} }
async function synthesize(f:any,sources:Source[],correction?:string){ if(!process.env.GROQ_API_KEY) throw new Error('GROQ_API_KEY is not configured.') ; const evidence=sources.map((s,i)=>`[S${i+1}] ${s.title} | ${s.sourceType} | ${s.url}\n${s.excerpt.slice(0,1800)}`).join('\n\n').slice(0,9000); const prompt=`You are FounderOS evidence analyst. Use ONLY the retrieved evidence below. Return JSON only, no markdown, with exactly these string keys: founderBackground, founderWhy, companyWhat, companyWhy, companyHow, whoItServes, currentStage, currentFocus, facts, inferences, unknowns, privateNoteClaims, depth, depthReason, askText. Cite every factual claim with [S#]. FACT means directly supported; INFERENCE means a cautious conclusion supported by multiple sources; UNKNOWN means not established. Never invent founder motivation, customers, traction, stage, or current focus. Search evidence specifically for why the founder started the company. Keep private notes as PRIVATE HYPOTHESIS and assess them only against evidence. depth must be exactly DEEP_RESEARCH_ASK, LIGHT_RESEARCH_ASK, LIMITED_INFORMATION_ASK, or SKIP. askText is a short, human LinkedIn draft based on the evidence, from an honest 18-year-old who wants to contribute and learn; do not ask for a job immediately, use buzzwords, exaggerate, or send anything. Founder: ${f.name}. Company: ${f.companyName}. Private hypothesis: ${f.privateNotes||'None'}.\n${correction||''}\nEVIDENCE:\n${evidence}`; const budget=researchConfig(); const requestedOutput=Math.min(budget.finalBudget,budget.totalBudget); if(estimateTokens(prompt)+requestedOutput>budget.totalBudget) throw new Error(`Research token budget would be exceeded before synthesis (${estimateTokens(prompt)} estimated input + ${requestedOutput} requested output).`); const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.GROQ_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model,temperature:0.1,max_tokens:Math.min(researchConfig().finalBudget, researchConfig().totalBudget),response_format:{type:'json_object'},messages:[{role:'system',content:'You produce strict evidence-grounded JSON for an internal research tool.'},{role:'user',content:prompt}]}),signal:AbortSignal.timeout(45000)}); if(!r.ok){ let detail=''; try { const body=await r.json(); detail=body?.error?.message||body?.error?.code||'' } catch {} throw new Error(`Groq request failed (${r.status})${detail?`: ${detail}`:''}.`) } const json=await r.json(); const text=json.choices?.[0]?.message?.content; const parsed=parseReport(text||'',f,sources.length); if(!parsed)throw new Error('Groq returned invalid FounderOS JSON.'); return parsed }
export async function POST(request:Request){ const {founderId}=await request.json(); const [f]=await db.select().from(founders).where(eq(founders.id,founderId)); if(!f)return NextResponse.json({error:'Founder not found.'},{status:404}); const state=initialState(); const trace:string[]=['Research started']; const [run]=await db.insert(researchRuns).values({founderId,state:JSON.stringify(state),trace:JSON.stringify(trace),budget:JSON.stringify(state.budget)}).returning(); await addTrace(run.id,founderId,'Research started'); await addTrace(run.id,founderId,'Mechanical filtering policy enabled','Six-month post cutoff, URL normalization, deduplication, and compact batches'); const sources:Source[]=[];
  lastBrightDataDiagnostics = undefined
  if (f.founderLinkedinUrl) {
    try { sources.push(...await collectBrightDataLinkedIn(f.founderLinkedinUrl, f.name)) }
    catch (error) { console.log('[v0] Bright Data collection failed:', error instanceof Error ? error.message : error) }
  }
  const discovered=discoverFromEvidence(sources)
  const discoveredName=discovered.companyName || f.companyName
  const supplied=[[f.companyWebsite,`${discoveredName} website`,'OFFICIAL WEBSITE'],[f.companyLinkedinUrl,`${discoveredName} LinkedIn`,'COMPANY PROFILE'],[discovered.companyWebsite,`${discoveredName} website`,'OFFICIAL WEBSITE'],[discovered.companyLinkedinUrl,`${discoveredName} LinkedIn`,'COMPANY PROFILE'],[f.founderLinkedinUrl,`${f.name} LinkedIn`,'FOUNDER PROFILE']].filter(x=>x[0]) as [string,string,string][]
  for(const [url,label,type] of supplied){const s=await readSource(url,label,type);if(s&&!sources.some(x=>x.url===s.url))sources.push(s)}
  const discoveryQueries=[`${f.founderLinkedinUrl} founder company`,`${f.name} founder company`,`${discoveredName} company founder`,`${discoveredName} LinkedIn`,`${discoveredName} YC`,`${discoveredName} website`,`${discoveredName} cofounder`]
  for(const q of discoveryQueries)for(const s of await searchPublic(q))if(!sources.some(x=>x.url===s.url))sources.push(s)
  const discoveredAgain=discoverFromEvidence(sources)
  const resolvedName=discoveredAgain.companyName || discoveredName
  const resolvedLinkedin=discoveredAgain.companyLinkedinUrl || f.companyLinkedinUrl || null
  const resolvedWebsite=discoveredAgain.companyWebsite || f.companyWebsite || null
  if(resolvedName!==f.companyName||resolvedLinkedin!==f.companyLinkedinUrl||resolvedWebsite!==f.companyWebsite){await db.update(founders).set({name:f.name==='Undiscovered founder'?(sources.find(s=>/FOUNDER PROFILE/i.test(s.sourceType))?.author||f.name):f.name,companyName:resolvedName,companyLinkedinUrl:resolvedLinkedin,companyWebsite:resolvedWebsite,updatedAt:new Date()}).where(eq(founders.id,founderId))}
  const resolvedFounder={...f,companyName:resolvedName,companyLinkedinUrl:resolvedLinkedin,companyWebsite:resolvedWebsite}
  const brightDataConfigured=Boolean(process.env.BRIGHTDATA_API_KEY)
  const filteredSources = mechanicalFilter(sources, state); const initialBatch = selectNextBatch(filteredSources, state, researchConfig()); updateMechanicalState(state, initialBatch, 'INSPECT_FOUNDER_PROFILE'); state.questions.COMPANY_WHAT={...state.questions.COMPANY_WHAT,evidenceCount:filteredSources.filter(s=>/COMPANY|WEBSITE|YC/i.test(s.sourceType)).length,lastUpdated:new Date().toISOString()}; state.questions.FOUNDER_BACKGROUND={...state.questions.FOUNDER_BACKGROUND,evidenceCount:filteredSources.filter(s=>/FOUNDER|LINKEDIN PROFILE/i.test(s.sourceType)).length,lastUpdated:new Date().toISOString()}; trace.push(`Mechanical filter retained ${filteredSources.length} compact evidence items`); trace.push(`Unresolved questions: ${unresolvedQuestions(state).join(', ') || 'none'}`); await addTrace(run.id, founderId, 'Evidence batch selected', `${filteredSources.length} new normalized, deduplicated items`); await addTrace(run.id, founderId, 'Research decision', `Highest-value unresolved questions: ${unresolvedQuestions(state).slice(0,4).join(', ') || 'none'}`); const linkedinSources=sources.filter(s=>s.provider==='Bright Data')
  const pipeline:Pipeline={webResearch:sources.length?'COMPLETE':'FAILED',sourcesCollected:sources.length,brightData:brightDataConfigured?(linkedinSources.length?'COMPLETE':'FAILED'):'NOT_CONFIGURED',founderProfile:linkedinSources.some(s=>s.sourceType==='LINKEDIN PROFILE'&&s.retrievalStatus==='FOUND')?'FOUND':f.founderLinkedinUrl?'NOT_FOUND':'NOT_ATTEMPTED',founderPosts:linkedinSources.filter(s=>s.sourceType==='LINKEDIN PUBLIC ACTIVITY'&&s.retrievalStatus==='FOUND').length,company:f.companyLinkedinUrl?'NOT_FOUND':'NOT_ATTEMPTED',companyPosts:0,coFoundersIdentified:0,coFounderPosts:0,groqSynthesis:'FAILED',modelUsed:model,structuredOutput:'INVALID',askGeneration:'FAILED',brightDataDiagnostics:lastBrightDataDiagnostics}; let report:Report; if(!sources.length){pipeline.error='No supplied page or public search result was accessible.';report=base(f,0)} else { try {report=await synthesize(resolvedFounder,initialBatch); pipeline.groqSynthesis='COMPLETE';pipeline.structuredOutput='VALID';pipeline.askGeneration='COMPLETE'} catch(first){ try {report=await synthesize(resolvedFounder,sources,'Correction: the previous response failed validation. Return only valid JSON with every required key as a string.');pipeline.groqSynthesis='COMPLETE';pipeline.structuredOutput='VALID';pipeline.askGeneration='COMPLETE'} catch(second){pipeline.error=second instanceof Error?second.message:'Groq synthesis failed.';report=base(f,sources.length)} } } const [saved]=await db.insert(researchReports).values({founderId,...report}).returning(); for(const s of sources)await db.insert(researchEvidence).values({founderId,reportId:saved.id,claimType:'SOURCE',claim:`${s.sourceType} — source collected for synthesis.`,sourceTitle:s.title,sourceUrl:s.url,excerpt:`Retrieved ${s.retrievedAt}\n${s.excerpt}`}); await db.update(founders).set({status:pipeline.groqSynthesis==='COMPLETE'?'ASK DRAFTED':'RESEARCHED',researchDepth:report.depth,askText:report.askText,updatedAt:new Date()}).where(eq(founders.id,founderId)); await db.insert(founderEvents).values({founderId,status:pipeline.groqSynthesis==='COMPLETE'?'ASK DRAFTED':'RESEARCHED',note:`${sources.length} sources collected. Web: ${pipeline.webResearch}. Groq: ${pipeline.groqSynthesis}. Structured output: ${pipeline.structuredOutput}.`}); return NextResponse.json({...saved,evidence:sources,pipeline}) }
