import { db } from '@/lib/db'
import { researchLlmCalls, researchRuns, researchTrace } from '@/lib/db/schema'
import { eq } from 'drizzle-orm'

export const ACTIONS = ['INSPECT_MORE_FOUNDER_POSTS','INSPECT_COMPANY_POSTS','INSPECT_YC','INSPECT_SPEEDRUN','INSPECT_COFOUNDER','INSPECT_OTHER_PUBLIC_SOURCE','STOP_RESEARCH'] as const
export type Action = typeof ACTIONS[number]
export type Evidence = { title:string; url:string; excerpt:string; sourceType:string; retrievedAt:string; author?:string; publishedAt?:string; provider?:string; retrievalStatus?:'FOUND'|'UNAVAILABLE' }
export type QuestionKey = 'FOUNDER_BACKGROUND'|'FOUNDER_WHY'|'COMPANY_WHAT'|'PRODUCT_HOW'|'CUSTOMER'|'CURRENT_STAGE'|'CURRENT_FOCUS'|'TRACTION'|'RECENT_ACTIVITY'|'FOUNDING_STORY'
export type QuestionState = { status:'UNKNOWN'|'PARTIAL'|'ANSWERED'|'HIGH_CONFIDENCE'; confidence:number; evidenceCount:number; importance:number; lastUpdated:string }
export type ResearchConfig = { maxIterations:number; totalBudget:number; stepBudget:number; finalBudget:number; askBudget:number; maxEvidenceItems:number; maxCharsPerEvidence:number; maxCalls:number }
export type ResearchState = { WHAT:string; WHY:string; HOW:string; CUSTOMER:string; CURRENT_STAGE:string; CURRENT_FOCUS:string; FOUNDER_MINDSET:string; TRACTION:string; FOUNDER_BACKGROUND:string; UNKNOWN:string[]; confidence:Record<string,'strong'|'moderate'|'weak'|'unknown'>; questions:Record<QuestionKey,QuestionState>; sourcesInspected:string[]; postsInspected:string[]; sourceTypesInspected:string[]; actionsTaken:string[]; postingPattern:'NO_POSTS'|'RARE'|'MONTHLY'|'WEEKLY'|'HIGH_FREQUENCY'|'DAILY_BUILDING_IN_PUBLIC'|'unknown'; budget:{calls:number; inputTokens:number; outputTokens:number; totalTokens:number; maxCalls:number; remaining:number}; depth:string; stopReason:string; discarded:{old:number; duplicate:number; malformed:number; redundant:number} }
const questionKeys:QuestionKey[] = ['FOUNDER_BACKGROUND','FOUNDER_WHY','COMPANY_WHAT','PRODUCT_HOW','CUSTOMER','CURRENT_STAGE','CURRENT_FOCUS','TRACTION','RECENT_ACTIVITY','FOUNDING_STORY']
export function researchConfig():ResearchConfig { const n=(key:string, fallback:number)=>{const value=Number(process.env[key]);return Number.isFinite(value)&&value>0?value:fallback}; return {maxIterations:n('FOUNDEROS_RESEARCH_MAX_ITERATIONS',5),totalBudget:n('FOUNDEROS_RESEARCH_LLM_BUDGET',6000),stepBudget:n('FOUNDEROS_RESEARCH_STEP_BUDGET',1200),finalBudget:n('FOUNDEROS_FINAL_SYNTHESIS_BUDGET',2500),askBudget:n('FOUNDEROS_ASK_BUDGET',800),maxEvidenceItems:n('FOUNDEROS_MAX_EVIDENCE_ITEMS',6),maxCharsPerEvidence:n('FOUNDEROS_MAX_CHARS_PER_EVIDENCE',1000),maxCalls:n('FOUNDEROS_RESEARCH_MAX_CALLS',5)} }
export const initialState = ():ResearchState => { const now=new Date().toISOString(); const questions=Object.fromEntries(questionKeys.map(key=>[key,{status:'UNKNOWN',confidence:0,evidenceCount:0,importance:(['FOUNDER_WHY','COMPANY_WHAT','PRODUCT_HOW','CURRENT_FOCUS'] as string[]).includes(key)?1:.6,lastUpdated:now}])) as Record<QuestionKey,QuestionState>; const c=researchConfig(); return {WHAT:'UNKNOWN',WHY:'UNKNOWN',HOW:'UNKNOWN',CUSTOMER:'UNKNOWN',CURRENT_STAGE:'UNKNOWN',CURRENT_FOCUS:'UNKNOWN',FOUNDER_MINDSET:'UNKNOWN',TRACTION:'UNKNOWN',FOUNDER_BACKGROUND:'UNKNOWN',UNKNOWN:[],confidence:{},questions,sourcesInspected:[],postsInspected:[],sourceTypesInspected:[],actionsTaken:[],postingPattern:'unknown',budget:{calls:0,inputTokens:0,outputTokens:0,totalTokens:0,maxCalls:c.maxCalls,remaining:c.totalBudget},depth:'',stopReason:'',discarded:{old:0,duplicate:0,malformed:0,redundant:0}} }
export function normalizeUrl(value:string){try{const u=new URL(value);u.hash='';u.search='';return u.toString().replace(/\/$/,'')}catch{return null}}
export function mechanicalFilter(raw:Evidence[], state:ResearchState, config=researchConfig()){ const cutoff=Date.now()-183*24*60*60*1000; const seen=new Set(state.sourcesInspected); const urls=new Set<string>(); let old=0,duplicate=0,malformed=0; const filtered=raw.filter(item=>{const url=normalizeUrl(item.url);if(!url||!item.excerpt||item.excerpt.length<30){malformed++;return false} if(seen.has(url)||urls.has(url)){duplicate++;return false} urls.add(url);item.url=url;const isPost=/POST|ACTIVITY/i.test(item.sourceType);if(isPost&&item.publishedAt&&Date.parse(item.publishedAt)<cutoff){old++;return false}return true}).sort((a,b)=>Date.parse(b.publishedAt||b.retrievedAt)-Date.parse(a.publishedAt||a.retrievedAt)); state.discarded.old+=old;state.discarded.duplicate+=duplicate;state.discarded.malformed+=malformed;return filtered.slice(0,config.maxEvidenceItems) }
export function compactEvidence(items:Evidence[], config=researchConfig()){ return items.slice(0,config.maxEvidenceItems).map((s,i)=>`[E${i+1}] ${s.title} | ${s.sourceType} | ${s.author||'unknown'} | ${s.publishedAt||'date unknown'} | ${s.url}\n${s.excerpt.slice(0,config.maxCharsPerEvidence)}`).join('\n\n') }
export function adaptiveBatches(items:Evidence[], state:ResearchState, config=researchConfig()){ const remaining=items.filter(item=>!state.sourcesInspected.includes(normalizeUrl(item.url)||'')); const limit=Math.min(3,config.maxEvidenceItems); const batches:Evidence[][]=[]; for(let i=0;i<remaining.length;i+=limit)batches.push(remaining.slice(i,i+limit)); return batches }
export function selectNextBatch(items:Evidence[], state:ResearchState, config=researchConfig()){ const batches=adaptiveBatches(items,state,config); return batches[0]||[] }
export function estimateTokens(value:string){return Math.ceil(value.length/4)}
export function canAfford(state:ResearchState,input:string,output:number){return state.budget.remaining>=estimateTokens(input)+output&&state.budget.calls<state.budget.maxCalls}
export function chooseModel(task:'EVIDENCE_ASSESSMENT'|'RESEARCH_DECISION'|'FINAL_SYNTHESIS'|'ASK_GENERATION', remaining:number){const configured=task==='FINAL_SYNTHESIS'?process.env.FOUNDEROS_SYNTHESIS_MODEL:task==='ASK_GENERATION'?process.env.FOUNDEROS_ASK_MODEL:process.env.FOUNDEROS_RESEARCH_MODEL;return configured||process.env.GROQ_MODEL||'openai/gpt-oss-20b'}
export function postingPattern(posts:Evidence[]):ResearchState['postingPattern'] { if(!posts.length)return 'NO_POSTS'; const dates=posts.map(p=>Date.parse(p.publishedAt||'')).filter(Number.isFinite).sort((a,b)=>a-b);if(dates.length<2)return 'RARE';const span=Math.max(1,(dates.at(-1)!-dates[0]!)/86400000);const perMonth=dates.length/(span/30);return perMonth>=20?'DAILY_BUILDING_IN_PUBLIC':perMonth>=8?'HIGH_FREQUENCY':perMonth>=3?'WEEKLY':perMonth>=1?'MONTHLY':'RARE' }
export function actionAllowed(action:string,state:ResearchState){return ACTIONS.includes(action as Action)&&!state.actionsTaken.includes(action)&&state.budget.calls<state.budget.maxCalls}
export function updateMechanicalState(state:ResearchState, evidence:Evidence[], action?:string){
  const now=new Date().toISOString();
  const posts=evidence.filter(item=>/POST|ACTIVITY/i.test(item.sourceType));
  state.sourcesInspected.push(...evidence.map(item=>normalizeUrl(item.url)).filter((url):url is string=>Boolean(url)));
  state.sourcesInspected=[...new Set(state.sourcesInspected)];
  state.postsInspected=[...new Set([...state.postsInspected,...posts.map(item=>normalizeUrl(item.url)).filter((url):url is string=>Boolean(url))])];
  state.sourceTypesInspected=[...new Set([...state.sourceTypesInspected,...evidence.map(item=>item.sourceType)])];
  if(action && !state.actionsTaken.includes(action)) state.actionsTaken.push(action);
  state.postingPattern=postingPattern(posts);
  state.questions.RECENT_ACTIVITY={...state.questions.RECENT_ACTIVITY,evidenceCount:state.postsInspected.length,lastUpdated:now};
  if(posts.length===0) state.questions.RECENT_ACTIVITY={...state.questions.RECENT_ACTIVITY,status:'UNKNOWN',confidence:0};
  return state;
}
export function unresolvedQuestions(state:ResearchState){return questionKeys.filter(key=>state.questions[key].status==='UNKNOWN'||state.questions[key].status==='PARTIAL').sort((a,b)=>state.questions[b].importance-state.questions[a].importance)}
export function stopReason(state:ResearchState){const core:QuestionKey[]=['COMPANY_WHAT','PRODUCT_HOW','CUSTOMER','CURRENT_FOCUS','FOUNDER_WHY'];const answered=core.filter(k=>state.questions[k].confidence>=.65).length;if(state.budget.remaining<200)return 'TOKEN_BUDGET_EXHAUSTED';if(state.budget.calls>=state.budget.maxCalls)return 'MAX_LLM_CALLS_REACHED';if(answered>=4)return 'CORE_QUESTIONS_ANSWERED';if(state.actionsTaken.length>=researchConfig().maxIterations)return 'MAX_RESEARCH_ITERATIONS';return 'UNRESOLVED_HIGH_VALUE_QUESTIONS'}
export function shouldStop(state:ResearchState){return stopReason(state)!=='UNRESOLVED_HIGH_VALUE_QUESTIONS'}
export function rateHeaders(h:Headers){const keys=['retry-after','x-ratelimit-limit-requests','x-ratelimit-remaining-requests','x-ratelimit-limit-tokens','x-ratelimit-remaining-tokens'];return Object.fromEntries(keys.map(k=>[k,h.get(k)]).filter(([,v])=>v!==null))}
export function extractUsage(payload:any){const u=payload?.usage||{};return {inputTokens:u.prompt_tokens??u.input_tokens,outputTokens:u.completion_tokens??u.output_tokens,totalTokens:u.total_tokens}}
export async function recordCall(runId:string, founderId:string, data:{stage:string;action?:string;model:string;inputTokens?:number;outputTokens?:number;totalTokens?:number;latencyMs:number;success:boolean;rateLimit?:unknown;error?:string}){await db.insert(researchLlmCalls).values({runId,founderId,stage:data.stage,action:data.action,model:data.model,inputTokens:String(data.inputTokens??''),outputTokens:String(data.outputTokens??''),totalTokens:String(data.totalTokens??''),latencyMs:String(data.latencyMs),success:data.success,rateLimit:JSON.stringify(data.rateLimit||{}),error:data.error})}
export async function saveRun(runId:string, state:ResearchState, trace:string[], stopReason?:string){await db.update(researchRuns).set({state:JSON.stringify(state),trace:JSON.stringify(trace),budget:JSON.stringify(state.budget),stopReason,updatedAt:new Date()}).where(eq(researchRuns.id,runId))}
export async function addTrace(runId:string,founderId:string,event:string,detail?:string,action?:string){await db.insert(researchTrace).values({runId,founderId,event,detail,action})}
export const benchmarkFixture='[E1] Founder personal post | LINKEDIN POST | Luke Wagner | 2026-02-01 | https://example.com/personal\nI left medical school after realizing I wanted to build tools for teams doing difficult work.\n[E2] Founder product post | LINKEDIN POST | Luke Wagner | 2026-03-01 | https://example.com/product\nLightfield gathers context and policies before legal work reaches in-house counsel.\n[E3] YC launch | YC ANNOUNCEMENT | Lightfield | 2026-01-15 | https://ycombinator.com/companies/lightfield\nLightfield is built for in-house legal teams and connects to email, chat and business systems.'
export { researchRuns }
